#!/bin/bash

# get hostname for target machine
echo -n "please enter your email so that we can follow up and see how it is going: "
read EMAIL

# create non root user with sudo privileges
if [ $(id -u) -eq 0 ]; then
    echo -n "This installation is not meant to run as root ... enter non root username with passwordless sudo: "
    read USERNAME
    if [ ! -d /home/$USERNAME ]; then
        useradd $USERNAME -u 1000 --shell "/bin/bash" && echo "$USERNAME:$USERNAME" | chpasswd && adduser $USERNAME sudo
        sed -i /etc/sudoers -re 's/^%sudo.*/%sudo   ALL=(ALL:ALL) NOPASSWD: ALL/g'
        mkdir /home/$USERNAME
        chown $USERNAME:$USERNAME /home/$USERNAME
        usermod -a -G docker $USERNAME

        echo 'You will still need to set up some authorized_keys'
        echo 'Also please sefile.zipt `PermitRootLogin no`'
        echo '`PasswordAuthentication no` and `ChallengeResponseAuthentication no`'
    fi
fi

#install a kubernetes
if ! kubectl get ns default >/dev/null 2>&1; then
    echo "Installing a kubernetes"
    if [[ -v K8S ]]; then
        #k3d
        echo "installing k3d"
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        k3d cluster create k3d-cluster
        # kubectl
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin
    else
        #k3s
        echo "installing k3s"
        curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $(id -u):$(id -g) ~/.kube/config

    fi
fi

# install helm

curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# add signoz

helm repo add signoz https://charts.signoz.io
kubectl create ns platform
helm --namespace platform install my-release signoz/signoz
sleep 3
echo "wait for signoz"
kubectl wait pod --all --for=condition=Ready --namespace=platform
helm install my-k8s-infra signoz/k8s-infra --set otelCollectorEndpoint=my-release-signoz-otel-collector:4317 -n platform
