- name: install knative
  hosts: localhost
  tasks:
# Download and apply manifest
  - name: Download custom resources.
    ansible.builtin.get_url:
      url: https://github.com/knative/serving/releases/download/knative-v1.16.0/serving-crds.yaml
      dest: /tmp/install/serving-crds.yaml
      mode: '0664'
  - name: install custom resources
    kubernetes.core.k8s:
      state: present
      src: /tmp/install/serving-crds.yaml
  - name: Download core components.
    ansible.builtin.get_url:
      url: https://github.com/knative/serving/releases/download/knative-v1.16.0/serving-core.yaml
      dest: /tmp/install/serving-core.yaml
      mode: '0664'
  - name: install core components
    kubernetes.core.k8s:
      state: present
      src: /tmp/install/serving-core.yaml
  - name: Download networking.
    ansible.builtin.get_url:
      url: https://github.com/knative/net-kourier/releases/download/knative-v1.16.0/kourier.yaml
      dest: /tmp/install/kourier.yaml
      mode: '0664'
  - name: install core components
    kubernetes.core.k8s:
      state: present
      src: /tmp/install/kourier.yaml
